services:
  #Define the services for the Node.js app
  backend:
    image: expense-tracker-backend
    build: #Build an image 
      context: ./    #Start from the root directory wrt to the dockerfile
      dockerfile: backend.dockerfile #Locate the dockerfile to build
    container_name: backend-expense-tracker
    ports:
      - "4000:4000"
    volumes:
      - ./:/app  #Map the source code from the root directory
    environment:
      - NODE_ENV=development
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
    networks:
      - expense-tracker-network
    depends_on:
      - mongodb #Ensures the 'mongo' service is started before the app service

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - expense-tracker-network

networks:
  expense-tracker-network:  #Docker creates a network (with deafult driver: bridge) if it doesn't exist 